### ISSUE TITLE
Multi-amp support to GT++ multis

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GTplusplus#106]
Add add multi-amp support to GT++ multis
Add TecTech Lasers to GT++ multis

is it realizable? if it is not needed please specify

**Comment by Sphyix** [comment]
Should be for every multi tbh.
Processing tier should be the laser tier, processing power and overclocks the max voltage

**Comment by GTNH-Colen** [comment]
The issue is tier skipping, we'd have to bring back something akin to energy cores to make it balanced (obviously with new recipes as the current set are absolute cancer).

**Comment by Sphyix** [comment]
Tier skipping is not an issue.
LuV 1million amps laser can only do LuV recipes.
UV laser can do up to UV recipes, etc..

**Comment by GTNH-Colen** [comment]
I don't think they obey that by default, you'd have to add special behaviour for it.

**Comment by Sphyix** [comment]
GT++ already does that on the nine in one multi

**Comment by GTNH-Afx237v7** [comment]
> I don't think they obey that by default, you'd have to add special behaviour for it.

You are right, tier skipping is a topic with laser hatches. They just tell the multi „consume all EU“ and it does just that. No problem to smelt UHV superconductor dust with an IV laser hatch (given you supply enough amps).

**Comment by FoKuCNiK** [comment]
It was a hint that lasers and multi-ampere hatches are almost never used in your assembly. I don't want my base to consist only of processing array and Bart dildo

**Comment by FoKuCNiK** [comment]
How many multiblocks support multi-amps or lasers? 5? 10? Where do I put all my energy?

**Comment by GTNH-Afx237v7** [comment]
Mega Blast Furnace, Mega Vacuum Freezer, and recently processing arrays were added.

**Comment by FoKuCNiK** [comment]
THIS is what I know. sick of them in my base...

**Comment by FoKuCNiK** [comment]
I want beauty, but I eat boxes

**Comment by draknyte1** [comment]
This repo isn’t a place for discussions on tickets.
