### ISSUE TITLE
Allow all biomes in Extended Book of Biomes to be obtainable using Rite of Shifting Seasons

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GTplusplus#109]
# Issue Title
Linked issue: https://github.com/alkcorp/WitcheryExtras/issues/15 (posted here by request)

As part of a broader GTNH bee rework I'd like to do once I get experience with Industrial Apiary / Mutatron, I think it would be cool if all biomes in the Extended Book of Biomes worked in Rite of Shifting Seasons. Currently the biomes are limited to only the base Book of Biomes, which doesn't include space and certain end and extra dim biomes. 

## Expected Behavior
All biomes detectable by Extended Book of Biomes should be usable in the Shifting Seasons Witchery ritual.

## Current Behavior
Book of Biomes does not include all biomes, which means glowstone counts for the Shifting Seasons ritual are unknown (and probably don't work if you include more glowstone, haven't checked).

## Possible Solution
Could make the biomes appear in the base Book of Biomes or add glowstone numbers to the Extended Book.

## Steps to Reproduce (for bugs)
N/A

## Context
The goal here is primarily to allow space bees to be bred in the OW.

Once the bee breeding requirements are changed to be biome-specific instead of dim specific (I would do this with the bee rework or get a GTNH dev to do it), this would allow an alternate route to breeding space bees. For example,
![image](https://user-images.githubusercontent.com/88752681/152428134-ddc1fe6b-6d1a-4efc-bd96-359c1a81f65f.png)

Ledox is currently obtainable (in GTNH) using space flower and UUM:
![image](https://user-images.githubusercontent.com/88752681/152428338-b13d0b9d-77f1-489d-83c3-598deff43ad4.png)

This would be cool for both variety of playstyles and helping progression in no-rocket.

This wouldn't break anything progression wise on its own, as bee requirements are still dim specific.

## Game Environment
Using GTNH 2.1.2.1 http://downloads.gtnewhorizons.com/ClientPacks/

 * Gregtech version: 5.0.9.40.16
 * IC2 version: 2.2.828-experimental
 * Java version: java 8 openjdk v1.8.0_312
 * Operating System: Ubuntu 20.04

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by chochem** [comment]
if this is still relevant, please make a ticket on https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues
