### ISSUE TITLE
Remove Certain Elemental Dust Recipe Outputs

### ISSUE THREAD

**Issue by Elisis** [GTNewHorizons/GTplusplus#117]
# Issue Title  
 Either alter or remove all outputs of elemental Lanthanum, Cerium, Yttrium, Gadolinium, Praeseodymium from Dehydrator, 
 Electrolyzer, and Centrifuge ore byproducts.

Either changing to another material that can be implemented further in the lanthanide line, akin to Bart's replacement of all references to Platinum from ore to PMPD, or outright removal works fine.

## Context
 This will assist in proper balance around the new lanthanide line.

**Comment by chochem** [comment]
if this is still relevant, please make a ticket on https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues
