### ISSUE TITLE
Include information that Large Sifter requires 4 output bus blocks to form

### ISSUE THREAD

**Issue by Zap0** [GTNewHorizons/GTplusplus#137]
# Issue Title  
A Large Sifter multiblock will not form without 4 output bus blocks.

## Expected Behavior
Why wouldn't it form with just one output bus anyway, really? The whole output comes out of one bus anyway.
Either way, I was stumped when the multi didn't form with just one output bus. There was no information that it required 4 in either the GT++ tab quest or the control block tooltip.

## Current Behavior
There is no information about this requirement that I could find.

## Possible Solution
Put some text in the controller tooltip and/or the relevant quest in questbook.
Or change it to only need one output bus, unless there's other reasons for that I don't know.

## Context
Trying to upgrade from a singleblock sifter to something better

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used: 2.1.2.1
 * Download Link if possible: https://discord.com/channels/181078474394566657/252440750174765057/922793626449371147

Also include:
 * Gregtech version:
 * IC2 version: 
 * Java version: 8
 * Operating System: W7

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Already fixed and reflected in tooltip.
