### ISSUE TITLE
Molecular transformer wrong energy usage

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GTplusplus#155]
## Expected Behavior
Expected it to use as much time as recipe states and that much ampreser

## Current Behavior
Atm uses 2 less time then in recipe and completly ignores amperes stated in recipe

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used: 2.3gf

**Comment by chochem** [comment]
the NEI page is still wrong in 2.4 5-dev.

It does not even make any sense by itself, the maths does not check out. E.g.,
![image](https://user-images.githubusercontent.com/40274384/174334302-339c69cf-c3a9-4194-839d-ce446acbd62b.png)
But using 15360 eu/t for 65.15 sec would mean a total cost of 20014080EU. As pointed out the actual recipe is just 1A, so using 7680 eu/t for 65.15s for 10007040. (so time and total EU are correct in NEI just not amperage or usage)

The 2x speed LewisSaber noticed is unrelated and actually correct, that comes from the speed bonus.

**Comment by GTNH-Afx237v7** [comment]
See also https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9972
