### ISSUE TITLE
GT++ Tree Growth Simulator & Zhuhai Fishing Port could have more info in NEI

### ISSUE THREAD

**Issue by Alrightsc** [GTNewHorizons/GTplusplus#168]
Tree Growth Simulator is not marked as a recipe catalyst (the side icon thing) for the TGS log recipes. Also they are missing total EU, EU/t, voltage, etc.

![tgs](https://user-images.githubusercontent.com/38641296/162635934-f8457e80-dec4-4886-b416-af28e41fd84c.png)

Zhuhai Fishing port in NEI does display recipes, but they only display the time and circuit required. It would be helpful if they could have voltage, EU/t, etc. like many other recipes that show them.

![zhuhai](https://user-images.githubusercontent.com/38641296/162635941-7e0881f1-40ca-43ea-8339-46620e348597.png)

**Comment by miozune** [comment]
Catalyst is added in #179

**Comment by chochem** [comment]
if this is still relevant, please make a ticket on https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues
