### ISSUE TITLE
Power sub-station doesn't output power for about a minute on world load

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GTplusplus#76]
# Issue Title  
The PSS experiences an issue on world load where it refuses to emit power for a short period when you start a single player save. 

## Expected Behavior
I expect the PSS to emit power at all times, if it's properly formed and otherwise functional.

## Current Behavior
On world load, the PSS doesn't emit power until it has had about a minute to load. (I don't know if the specific time frame is important; it may be a function of world size or modpack complexity.)

## Possible Solution
On world load, when paying close attention to the WAILA tooltip for the PSS, I noticed that it initially showed a status of Running Fine. Then, a short time later, the status switched to *** INCOMPLETE STRUCTURE ***. 

![javaw_1ix8TZPwp3](https://user-images.githubusercontent.com/33518699/147369531-b4b7a54e-bdc5-4c37-ab2d-64add31936b4.png)

Once the world had done more loading, and I was able to access the PSS's GUI, I noticed that, for a brief moment, it showed Error Code 64. 

![javaw_0yX9yZlxyK](https://user-images.githubusercontent.com/33518699/147369543-02946fb4-5724-4491-922c-2f23b38767e9.png)

Then, it showed a status of "Running Fine" and was able to output power normally.

## Steps to Reproduce (for bugs)
With a fully formed PSS (and power inside,) close the minecraft instance entirely, then restart it and load the world.

## Game Environment
GT++ version: 1.7.23
GregTech version: 5.09.30.16
Java version: graalvm-ce-java8-21.1.0
IC2 version: 2.2.828-experimental
Operating system: Windows 10 Pro 

Observed in the GregTech New Horizons pack, version 2.1.2.1.

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
So after investigations, it seems onRunningTick() may take a while to be called.
I don't really know how to get around this as it's the behaviour of GT on all multis.
The controller waits 5s and then checks the structure/etc.
