### ISSUE TITLE
Fix some miscellaneous structurelib migration issues

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GTplusplus#77]
# Issue Title  
Two multiblocks are exhibiting some issues after being ported to StructureLib.
* The multiblock extruder strictly requires the muffler hatch to be on the back center, opposite the controller.
* The maceration stack is "borked." I have no context for this and haven't personally demonstrated the specific issue.

## Game Environment
GTNH 2.1.2.1. 

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x ]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by Florexiz** [comment]
Dangote Distillus also doesn't output fluids after migration
