### ISSUE TITLE
GUI suggestion for Overflow Valves

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GTplusplus#84]
## Expected Behavior
Add a GUI for overflow valves that allows you to enter a specific value and can be opened by shift right clicking with empty hand.

## Current Behavior
Need to change the value by right clicking with empty hand or a screwdriver.

## Context
A GUI that allows you to enter a specific value would be more convenient for the user.

### Misc Info
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by YannickMG** [comment]
Are  you using the pack? If so on what version?

Currently it appears to have such a shift-right-click GUI.

![image](https://user-images.githubusercontent.com/5321549/148705212-8f1f0094-10a8-43ee-b046-574a2f075dcf.png)

**Comment by YannickMG** [comment]
This was implemented in https://github.com/GTNewHorizons/GTplusplus/commit/d82c412d6749d825dc952f98e3a22dfee93c0fa1 for context so using the latest release should let you use this,
